version: '3.9'
services:
  frontend:
    working_dir: /usr/src/app
    build:
      context: .
      dockerfile: ./dockerfile/frontend/Dockerfile
    ports:
      - "8020:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /usr/src/app
    tty: true

  backend:
    working_dir: /usr/src/app
    build: 
      context: .
      dockerfile: ./dockerfile/backend/Dockerfile
    ports:
      - "8010:80"
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
    tty: true
