version: '3.9'
services:
  backend:
    working_dir: /usr/src/app
    build: 
      context: .
      dockerfile: ./dockerfile/backend/Dockerfile
    ports:
      - "8010:80"
    volumes:
      - type: bind
        source: ./backend
        target: /usr/src/app
    tty: true
